config/routes.rb
Rails.application.routes.draw do
  resources :monkeys
  resources :songs do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monkey.rb
class Monkey < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :song
  validates :content, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :reviews
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  before_action :set_monkey, only: [:show, :edit, :update, :destroy]

  # GET /monkeys
  # GET /monkeys.json
  def index
    @monkeys = Monkey.all
  end

  # GET /monkeys/1
  # GET /monkeys/1.json
  def show
  end

  # GET /monkeys/new
  def new
    @monkey = Monkey.new
  end

  # GET /monkeys/1/edit
  def edit
  end

  # POST /monkeys
  # POST /monkeys.json
  def create
    @monkey = Monkey.new(monkey_params)

    respond_to do |format|
      if @monkey.save
        format.html { redirect_to @monkey, notice: 'Monkey was successfully created.' }
        format.json { render :show, status: :created, location: @monkey }
      else
        format.html { render :new }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monkeys/1
  # PATCH/PUT /monkeys/1.json
  def update
    respond_to do |format|
      if @monkey.update(monkey_params)
        format.html { redirect_to @monkey, notice: 'Monkey was successfully updated.' }
        format.json { render :show, status: :ok, location: @monkey }
      else
        format.html { render :edit }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monkeys/1
  # DELETE /monkeys/1.json
  def destroy
    @monkey.destroy
    respond_to do |format|
      format.html { redirect_to monkeys_url, notice: 'Monkey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monkey
      @monkey = Monkey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monkey_params
      params.require(:monkey).permit(:name)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_song

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.song = @song
    if @review.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  private

  def set_song
    @song = Song.find(params[:song_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # READ
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizAnswers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monkeys/_form.html.erb
<%= form_with(model: monkey, local: true) do |form| %>
  <% if monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% monkey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monkeys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monkeys.each do |monkey| %>
      <tr>
        <td><%= monkey.name %></td>
        <td><%= link_to 'Show', monkey %></td>
        <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
        <td><%= link_to 'Destroy', monkey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monkey.name %>
</p>

<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>

app/views/songs/edit.html.erb
<h1>Song Form</h1>
<%= form_for @song do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/songs/new.html.erb
<h1>Song Form</h1>
<%= form_for @song do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p><%= @song.year %></p>
<p><%= @song.category %></p>

<h2>Here are the reviews for this song:</h2>

<ul>
  <% @song.reviews.each do |review| %>
    <li><%= @review.content %></li>
  <% end %>
</ul>